config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'splash#index'
  
  resources :users
  
  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :users, except: [:new, :edit]
      post 'sign_in' => 'users#sign_in'
      resources :splash 
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# User model
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create -> { self.auth_token = SecureRandom.hex }

  def all_posts
    posts.all
  end

  def new_post
    @post = posts.new
  end

  def new_post_with_params(parameters)
    @post = posts.new parameters
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_filter :authenticate_user_from_token, :only => [:create, :sign_in]
  skip_before_filter :authenticate_user!
  skip_before_filter :verify_authenticity_token

  rescue_from ActiveRecord::RecordInvalid do |e|
    render json: {error: {RecordInvalid: e.record.errors}}, status: 422
  end

  # POST /users.json
  def create
    if User.find_by(email: user_params[:email])
      render :json => {error: 'Email address already registered'}, status: 422
      return
    end
    user = User.create user_params
    if user.valid?
      render :json =>  {user: user}
    else
      render json: {error: 'Oops!  Lazy error handling on the rails side :/'}, status: 422
    end
  end

  def sign_in
    user = User.find_by(email: user_params[:email])
    if user && user.valid_password?(user_params[:password])
      render :json => {user: user}
    else
      render json: {error: 'Incorrect credentials'}, status: 401
    end
  end

  def index
    render :json => {user: current_user}
  end

  def update
    current_user.update user_params
    render :json => current_user
  end

  def destroy
    User.find(current_user.id).destroy
    render :json => {status: 'Deregistered!'}, status: 200
  end


  def user_params
      params.require(:user).permit(:email, :password, :password_confirmation,
      :username, :auth_token, :created_at, :current_sign_in_at)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, :if => :format_html?
  before_filter :authenticate_user_from_token, :unless => :format_html?
  # I'm not sure what this does, but it fixed the JSON requests...at some point.  
  # Now it looks like I can do whatever I want with this gone.  I'll leave it for now, until I get
  # to adding some tests, and will see if it's important then.
  before_filter :configure_permitted_parameters, if: :devise_controller?, :unless => :format_html?
  
  
  def format_html?
    request.format.html?
  end
  
  def authenticate_user_from_token
    unless authenticate_with_http_token do |token|
      if @current_user = User.find_by(auth_token: token)
        return @current_user
      end
    end
      render json: { error: 'Bad Token'}, status: 401
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = current_user.all_posts
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.new_post
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    # @post = Post.new(post_params)
    @post = current_user.new_post_with_params post_params
    @post.user_id = current_user.id
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_filter :authenticate_user!
  
  def index
  end
end

app/controllers/users_controller.rb
# The users controller
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_filter :verify_authenticity_token

  # GET /users
  # GET /users.json
  def index
    @user = current_user
    @posts = current_user.all_posts
  end

  # GET /users/1
  # GET /users/1.json
  def show
    logger.info("In show, user is #{@user}")
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new user_params
  end

  # Internal: respond to a create request
  def do_create
    respond_to do |format|
      if @user.save
        format_html 'User was successfully created.'
        format.json { render :show, status: :created, location: @user }
      else
        respond_with_error :new
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update user_params
        format_html 'User was successfully updated.'
        format.json { render :show, status: :ok, location: @user }
      else
        respond_with_error :edit
      end
    end
  end

  # Internal: sends appropriate variables to an html request
  def format_html(message)
    format.html do
      redirect_to @user, notice: message
    end
  end

  # Internal: compiles an error method in both html and json
  def respond_with_error(method)
    format.html { render method }
    format.json { render json: @user.errors, status: :unprocessable_entity }
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html do
        redirect_to users_url,
                    notice: 'User was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow
  # the white list through.
  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
  title The Slash &amp Hyphen
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" rel="stylesheet"
  = csrf_meta_tags
  body
  header.navbar.navbar-fixed-top.navbar-inverse

  = yield

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :user
    = f.text_field :user
  .actions = f.submit

app/views/posts/_view.html.slim
.card-columns
  .card-deck-wrapper
    .card-deck
      - @posts.each do |post|
        .card
          img.card-img-top alt=("Card image cap") src="assets/placeholder.jpg"
          .card-block
            h4.card-title = post.title.html_safe
            p.card-text = strip_tags post.content
            .btn.btn-primary = link_to "Edit", :controller => "posts", :action => "update", :id => post

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
center
  h1 Listing posts
  = render "view"
  = link_to 'New Post', new_post_path, class: "btn btn-secondary"
  
  
  
// Saving this because I can use the routing as an example.  It would be pretty
// easy to figure out, but it's here, why not keep it for the nonce
//
// table
//   thead
//     tr
//       th Title
//       th Content
//       th User
//       th
//       th
//       th

//   tbody
//     - @posts.each do |post|
//       tr
//         td = post.title
//         td = post.content
//         td = post.user
//         td = link_to 'Show', post
//         td = link_to 'Edit', edit_post_path(post)
//         td = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

// br

  

app/views/posts/new.html.slim
= javascript_include_tag Ckeditor.cdn_url

center
    h1 New post
    .container
        = bootstrap_form_for @post do |p|
                = p.text_area :title, :placeholder => "This is where you would put your title...", hide_label: true
                br
                = p.cktext_area :content, :class => "content"
                br
                = p.submit

//Kinda thinking I don't need this...
//= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:
  = @post.title
p
  strong Content:
  = @post.content
p
  strong User:
  = @post.user

= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path

app/views/splash/index.html.slim
center
  h1 Welcome to Saplyn!
  = button_to 'Dashboard!', users_path, :method => "get"

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

= link_to 'Show', @user
'|
= link_to 'Back', users_path

app/views/users/index.html.slim
center
  h1 User Space!
  h2 Welcome to User Space, #{@user.email}
  
  = button_to 'Add Post', new_post_url, :method => "get"
  
  = render "posts/view"

app/views/users/new.html.slim
= javascript_include_tag Ckeditor.cdn_url

h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice


= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path